# Site settings
title: Footnote to time.
header-img: img/home-bg.jpg
email: huc1011@qq.com
description: "A blog about software craft, engineering and spirit."
baseurl: ""
url: "http://nickolashu.github.io/"
twitter_username: Nickolas_OMG
github_username:  NickolasHu
facebook_username:  Nickolas

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems:  [jekyll-sitemap]
